name: artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
      - name: upload-artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: .github
          name: github-hidden
