name: "Multiplatform time"

on:  push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: time on linux
        run: date
  
  windows:
    runs-on: windows-latest
    steps:
      - name: time on windows
        run: Get-Date
  macos:
    runs-on: macos-latest
    steps:
      - name: time on mac
        run: date
  macos-not-latest:
    runs-on: macos-10.15
    needs: [linux, windows, macos]
    steps:
      - name: time on mac
        run: date
    
