name: py-artifact

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Run python script
      run: python hello.py
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: create artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build
        path: .
